# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
# Load "cities.csv" file
# change the csv file later to full list

cities_to_load = "output_data/cities.csv"

# Read "cities" Data File and store into Pandas DataFrames

cities_df = pd.read_csv(cities_to_load)

cities_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,Xining,36.6167,101.7667,18.32,54,75,0.96,CN,1663390824
1,1,Ponta Do Sol,32.6667,-17.1000,23.17,74,21,4.21,PT,1663390994
2,2,Broome,42.2506,-75.8330,15.47,87,100,1.54,US,1663390994
3,3,Soyo,-6.1349,12.3689,22.74,90,82,2.60,AO,1663390995
4,4,Rikitea,-23.1203,-134.9692,22.53,73,0,7.75,PF,1663390995

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
# Configure gmaps with API key

gmaps.configure(api_key=g_key)

# Delete NaN values and convert Humidity to float and store

cities_df = cities_df.dropna()
humidity = cities_df["Humidity"].astype(float)

# Store 'Latitude' and 'Longitude' into  locations.

locations = cities_df[["Lat", "Lng"]].astype(float)

# Create a humidity Heatmap layer

fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=max(cities_df["Humidity"]),
                                 point_radius = 2)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [4]:
# Narrow down the DataFrame to find your ideal weather condition.

filtered_cities_df = cities_df

# Drop any rows that don't contain all three conditions. Want to be sure the weather is ideal.
# A max temperature lower than 27 degrees but higher than 21

filtered_cities_df = filtered_cities_df.loc[(filtered_cities_df["Max Temp"] < 27) & (filtered_cities_df["Max Temp"] > 21)]

# Wind speed less than 10 mph

filtered_cities_df = filtered_cities_df.loc[filtered_cities_df["Wind Speed"] < 4.5]

# Zero cloudiness

filtered_cities_df = filtered_cities_df.loc[filtered_cities_df["Cloudiness"] == 0]

# Drop any rows with null values

filtered_cities_df = filtered_cities_df.dropna()

filtered_cities_df

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
71,71,Imuris,30.7833,-110.8667,23.41,40,0,1.45,MX,1663391012
72,72,Marbella,36.5154,-4.8858,22.36,11,0,1.15,ES,1663390860
111,111,Ambovombe,-25.1667,46.0833,21.67,62,0,2.90,MG,1663391023
141,141,Griffith,41.5284,-87.4237,22.96,81,0,2.06,US,1663391033
177,177,Tukrah,32.5341,20.5791,23.52,49,0,1.08,LY,1663391042
233,233,Rosetta,31.4044,30.4164,24.57,67,0,1.21,EG,1663391057
266,266,Cap Malheureux,-19.9842,57.6142,24.15,63,0,3.58,MU,1663391067
300,300,Yucca Valley,34.1142,-116.4322,24.29,34,0,3.58,US,1663391079
308,308,Qazvin,36.2797,50.0049,22.25,30,0,2.00,IR,1663391081
319,319,Benghazi,32.1167,20.0667,24.51,54,0,2.94,LY,1663391084
322,322,Alice Springs,-23.7000,133.8833,23.75,23,0,3.60,AU,1663390808
331,331,Yulara,-25.2406,130.9889,24.22,14,0,2.10,AU,1663391043
339,339,Alanya,36.5438,31.9998,22.07,54,0,2.00,TR,1663391088
351,351,Havelock,34.8791,-76.9013,21.64,90,0,1.98,US,1663391092
354,354,Angoche,-16.2325,39.9086,24.31,66,0,1.25,MZ,1663391093
372,372,Marsa Matruh,31.3525,27.2453,22.41,64,0,1.77,EG,1663391097
375,375,Belmonte,-15.8631,-38.8828,21.31,85,0,2.06,BR,1663391099
412,412,Osmaniye,37.0742,36.2478,26.11,61,0,0.79,TR,1663391110
437,437,Selma,36.5708,-119.6121,24.03,64,0,0.00,US,1663391117
452,452,San Angelo,31.4638,-100.4370,26.61,61,0,4.12,US,1663391122
460,460,Los Llanos De Aridane,28.6585,-17.9182,21.86,81,0,4.12,ES,1663391124
480,480,Zhangye,38.9342,100.4517,24.96,28,0,1.70,CN,1663390930
485,485,Chokwe,-24.5333,32.9833,21.54,57,0,3.44,MZ,1663391130
493,493,Kashan,33.9831,51.4364,26.75,26,0,3.41,IR,1663391132
522,522,Hami,42.8000,93.4500,25.26,11,0,0.95,CN,1663390909
568,568,Santa Ana,33.7456,-117.8678,22.86,81,0,1.54,US,1663391156
575,575,Batavia,41.8500,-88.3126,22.17,81,0,2.57,US,1663391158

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [5]:
hotel_df = filtered_cities_df

# params dictionary to update each iteration
params = {
    "radius": 5000,
    "types": "hotel",
    "key": g_key
}

for index, row in hotel_df.iterrows():
    # get lat, lng from df
    lat = row["Lat"]
    lng = row["Lng"]

    # change location each iteration while leaving original params in place
    
    params["location"] = f"{lat},{lng}"
    
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # assemble url and make API request
    
    print(f"Retrieving Results for Index {index}: {row['City']}.")
    response = requests.get(base_url, params=params).json()
    # print(json.dumps(response, indent=4, sort_keys=True))
    
    # extract results
    results = response['results']
    
    try:
        print(f"Closest hotel is {results[0]['name']}.")
        hotel_df.loc[index, 'Hotel Name'] = results[0]['name']
        
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        
    print("------------")

Retrieving Results for Index 71: Imuris.
Closest hotel is Ímuris.
------------
Retrieving Results for Index 72: Marbella.
Closest hotel is Marbella.
------------
Retrieving Results for Index 111: Ambovombe.
Closest hotel is Ambovombe.
------------
Retrieving Results for Index 141: Griffith.
Closest hotel is Gary.
------------
Retrieving Results for Index 177: Tukrah.
Closest hotel is Tocra.
------------
Retrieving Results for Index 233: Rosetta.
Closest hotel is Rasheed.
------------
Retrieving Results for Index 266: Cap Malheureux.
Closest hotel is Grand Baie.
------------
Retrieving Results for Index 300: Yucca Valley.
Closest hotel is Yucca Valley.
------------
Retrieving Results for Index 308: Qazvin.
Closest hotel is Qazvin.
------------
Retrieving Results for Index 319: Benghazi.
Closest hotel is Benghazi.
------------
Retrieving Results for Index 322: Alice Springs.
Closest hotel is Alice Springs.
------------
Retrieving Results for Index 331: Yulara.
Closest hotel is Petermann.
------------
Retrieving Results for Index 339: Alanya.
Closest hotel is Alanya.
------------
Retrieving Results for Index 351: Havelock.
Closest hotel is Havelock.
------------
Retrieving Results for Index 354: Angoche.
Closest hotel is Angoche Island.
------------
Retrieving Results for Index 372: Marsa Matruh.
Closest hotel is Marsa Matruh.
------------
Retrieving Results for Index 375: Belmonte.
Closest hotel is Belmonte.
------------
Retrieving Results for Index 412: Osmaniye.
Closest hotel is Osmaniye.
------------
Retrieving Results for Index 437: Selma.
Closest hotel is Selma.
------------
Retrieving Results for Index 452: San Angelo.
Missing field/result... skipping.
------------
Retrieving Results for Index 460: Los Llanos De Aridane.
Closest hotel is Los Llanos.
------------
Retrieving Results for Index 480: Zhangye.
Closest hotel is Zhangye.
------------
Retrieving Results for Index 485: Chokwe.
Closest hotel is Chokwe.
------------
Retrieving Results for Index 493: Kashan.
Closest hotel is Kashan.
------------
Retrieving Results for Index 522: Hami.
Closest hotel is Hami.
------------
Retrieving Results for Index 568: Santa Ana.
Closest hotel is Santa Ana.
------------
Retrieving Results for Index 575: Batavia.
Closest hotel is Aurora.
------------

In [6]:
hotel_df

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
71,71,Imuris,30.7833,-110.8667,23.41,40,0,1.45,MX,1663391012,Ímuris
72,72,Marbella,36.5154,-4.8858,22.36,11,0,1.15,ES,1663390860,Marbella
111,111,Ambovombe,-25.1667,46.0833,21.67,62,0,2.90,MG,1663391023,Ambovombe
141,141,Griffith,41.5284,-87.4237,22.96,81,0,2.06,US,1663391033,Gary
177,177,Tukrah,32.5341,20.5791,23.52,49,0,1.08,LY,1663391042,Tocra
233,233,Rosetta,31.4044,30.4164,24.57,67,0,1.21,EG,1663391057,Rasheed
266,266,Cap Malheureux,-19.9842,57.6142,24.15,63,0,3.58,MU,1663391067,Grand Baie
300,300,Yucca Valley,34.1142,-116.4322,24.29,34,0,3.58,US,1663391079,Yucca Valley
308,308,Qazvin,36.2797,50.0049,22.25,30,0,2.00,IR,1663391081,Qazvin
319,319,Benghazi,32.1167,20.0667,24.51,54,0,2.94,LY,1663391084,Benghazi
322,322,Alice Springs,-23.7000,133.8833,23.75,23,0,3.60,AU,1663390808,Alice Springs
331,331,Yulara,-25.2406,130.9889,24.22,14,0,2.10,AU,1663391043,Petermann
339,339,Alanya,36.5438,31.9998,22.07,54,0,2.00,TR,1663391088,Alanya
351,351,Havelock,34.8791,-76.9013,21.64,90,0,1.98,US,1663391092,Havelock
354,354,Angoche,-16.2325,39.9086,24.31,66,0,1.25,MZ,1663391093,Angoche Island
372,372,Marsa Matruh,31.3525,27.2453,22.41,64,0,1.77,EG,1663391097,Marsa Matruh
375,375,Belmonte,-15.8631,-38.8828,21.31,85,0,2.06,BR,1663391099,Belmonte
412,412,Osmaniye,37.0742,36.2478,26.11,61,0,0.79,TR,1663391110,Osmaniye
437,437,Selma,36.5708,-119.6121,24.03,64,0,0.00,US,1663391117,Selma
452,452,San Angelo,31.4638,-100.4370,26.61,61,0,4.12,US,1663391122,NaN
460,460,Los Llanos De Aridane,28.6585,-17.9182,21.86,81,0,4.12,ES,1663391124,Los Llanos
480,480,Zhangye,38.9342,100.4517,24.96,28,0,1.70,CN,1663390930,Zhangye
485,485,Chokwe,-24.5333,32.9833,21.54,57,0,3.44,MZ,1663391130,Chokwe
493,493,Kashan,33.9831,51.4364,26.75,26,0,3.41,IR,1663391132,Kashan
522,522,Hami,42.8000,93.4500,25.26,11,0,0.95,CN,1663390909,Hami
568,568,Santa Ana,33.7456,-117.8678,22.86,81,0,1.54,US,1663391156,Santa Ana
575,575,Batavia,41.8500,-88.3126,22.17,81,0,2.57,US,1663391158,Aurora

In [7]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap

info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [8]:
# Add marker layer on top of heat map

markers = gmaps.marker_layer(locations,display_info_box = True, info_box_content=hotel_info)

# Add the layer to the map

fig.add_layer(markers)
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(height='420px'))